name: Inputs demo
# If we want to use the Inputs then we need to define manual trigger.
on:
  workflow_dispatch:
    inputs:
      environment:
        description: Choose the environment to deploy to
        required: true
        default: dev
jobs:
  input-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy the App
        run: echo "Deploying the application to ${{ inputs.environment}}!"