name: Inputs demo
# If we want to use the Inputs then we need to define manual trigger.
on:
  workflow_dispatch:
    inputs:
      environment:
        description: Choose the environment to deploy to
        required: true
        default: dev
        type: choice
        options:
          - dev
          - test
          - prod
      artifact_tag:
        description: Choose the tag to deploy
        required: true
        default: v1.0.0
jobs:
  input-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy the App
        run: echo "Deploying the ${{ inputs.artifact_tag }} application to ${{ inputs.environment}}!"