name: Hello world!
on:
  push:
    branches:
      - developer
      - main
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
     - name: Introdducing variables
       run: echo "Hello, ${{ var.My_Name }}!"
  