name: Hello world!
on:
  push:
    branches:
      - developer
      - main
jobs:
  variable_demo:
   runs-on: ubuntu-latest
   steps:
     - name: Introdducing variables
       run: echo "Hello, ${{ vars.My_Name }}!"
  secrets_demo:
   runs-on: ubuntu-latest
   steps:
     - name: Introducing secrets
       run: echo "Hello, ${{ secrets.DOCKER_PASSWORD }}!"
  action_demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Print the index.html
        run: cat index.html
  